### ISSUE TITLE
scancode-licensedb needs more visibility to internet searches

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/scancode-licensedb#18]
I put `LDPL v2.0`  in the search field on Firefox and it very nicely gave me the public DejaCode link followed by the original LDPL project license link, but nothing about the licensedb entry, which is
https://scancode-licensedb.aboutcode.org/ldpl-2.0.html

As an additional consideration (another ticket perhaps) it might be useful to provide the DejaCode public link on all the licensedb license entries in an "Other URLs" field.  

<img width="771" alt="Screen Shot 2021-10-28 at 09 46 16" src="https://user-images.githubusercontent.com/4991620/139302208-c28e7496-10f1-4010-afad-ac80d73d7a84.png">

**Comment by pombredanne** [comment]
As of now, this comes at the top: https://www.google.com/search?q="LDPL v2.0"&pws=0&gl=us&gws_rd=cr
Eventually Google index was updated ... Closing!
